export const dummydata = [
  {
    img: "/demo.jpg",
    title: "Blog post title",
    body: "dxfcgvhbjhgvfcdfxfghksdbwgfvsdgjhfjbfuirfgaeugfbaegrtcfvgbhjnhfddtfcgvhbjnewrxctfvghbjbvfsxdfcgh",
    createdAt: "abcasdfwwsdgawdga",
    slug: "1234567890",
    id: 1,
    user: {
      img: "/user.png",
      username: "Pavan",
      id: "123",
    },
  },
  {
    img: "/demo.jpg",
    title: "Blog post title",
    body: "dxfcgvhbjhgvfcdfxfghksdbwgfvsdgjhfjbfuirfgaeugfbaegrtcfvgbhjnhfddtfcgvhbjnewrxctfvghbjbvfsxdfcgh",
    createdAt: "abcasdfwwsdgawdga",
    slug: "1234567890",
    id: 2,
    user: {
      img: "/user.png",
      username: "Pavan",
      id: "123",
    },
  },
  {
    img: "/demo.jpg",
    title: "Blog post title",
    body: "dxfcgvhbjhgvfcdfxfghksdbwgfvsdgjhfjbfuirfgaeugfbaegrtcfvgbhjnhfddtfcgvhbjnewrxctfvghbjbvfsxdfcgh",
    createdAt: "abcasdfwwsdgawdga",
    slug: "1234567890",
    id: 3,
    user: {
      img: "/user.png",
      username: "Pavan",
      id: "123",
    },
  },
  {
    img: "/demo.jpg",
    title: "Blog post title",
    body: "dxfcgvhbjhgvfcdfxfghksdbwgfvsdgjhfjbfuirfgaeugfbaegrtcfvgbhjnhfddtfcgvhbjnewrxctfvghbjbvfsxdfcgh",
    createdAt: "abcasdfwwsdgawdga",
    slug: "1234567890",
    id: 4,
    user: {
      img: "/user.png",
      username: "Pavan",
      id: "123",
    },
  },
  {
    img: "/demo.jpg",
    title: "Blog post title",
    body: "dxfcgvhbjhgvfcdfxfghksdbwgfvsdgjhfjbfuirfgaeugfbaegrtcfvgbhjnhfddtfcgvhbjnewrxctfvghbjbvfsxdfcgh",
    createdAt: "abcasdfwwsdgawdga",
    slug: "1234567890",
    id: 5,
    user: {
      img: "/user.png",
      username: "Pavan",
      id: "123",
    },
  },
  {
    img: "/demo.jpg",
    title: "Blog post title",
    body: "dxfcgvhbjhgvfcdfxfghksdbwgfvsdgjhfjbfuirfgaeugfbaegrtcfvgbhjnhfddtfcgvhbjnewrxctfvghbjbvfsxdfcgh",
    createdAt: "abcasdfwwsdgawdga",
    slug: "1234567890",
    id: 6,
    user: {
      img: "/user.png",
      username: "Pavan",
      id: "123",
    },
  },
  {
    img: "/demo.jpg",
    title: "Blog post title",
    body: "dxfcgvhbjhgvfcdfxfghksdbwgfvsdgjhfjbfuirfgaeugfbaegrtcfvgbhjnhfddtfcgvhbjnewrxctfvghbjbvfsxdfcgh",
    createdAt: "abcasdfwwsdgawdga",
    slug: "1234567890",
    id: 7,
    user: {
      img: "/user.png",
      username: "Pavan",
      id: "123",
    },
  },
  {
    img: "/demo.jpg",
    title: "Blog post title",
    body: "dxfcgvhbjhgvfcdfxfghksdbwgfvsdgjhfjbfuirfgaeugfbaegrtcfvgbhjnhfddtfcgvhbjnewrxctfvghbjbvfsxdfcgh",
    createdAt: "abcasdfwwsdgawdga",
    slug: "1234567890",
    id: 8,
    user: {
      img: "/user.png",
      username: "Pavan",
      id: "123",
    },
  },
  {
    img: "/demo.jpg",
    title: "Blog post title",
    body: "dxfcgvhbjhgvfcdfxfghksdbwgfvsdgjhfjbfuirfgaeugfbaegrtcfvgbhjnhfddtfcgvhbjnewrxctfvghbjbvfsxdfcgh",
    createdAt: "abcasdfwwsdgawdga",
    slug: "1234567890",
    id: 9,
    user: {
      img: "/user.png",
      username: "Pavan",
      id: "123",
    },
  },
  {
    img: "/demo.jpg",
    title: "Blog post title",
    body: "dxfcgvhbjhgvfcdfxfghksdbwgfvsdgjhfjbfuirfgaeugfbaegrtcfvgbhjnhfddtfcgvhbjnewrxctfvghbjbvfsxdfcgh",
    createdAt: "abcasdfwwsdgawdga",
    slug: "1234567890",
    id: 10,
    user: {
      img: "/user.png",
      username: "Pavan",
      id: "123",
    },
  },
  {
    img: "/demo.jpg",
    title: "Blog post title",
    body: "dxfcgvhbjhgvfcdfxfghksdbwgfvsdgjhfjbfuirfgaeugfbaegrtcfvgbhjnhfddtfcgvhbjnewrxctfvghbjbvfsxdfcgh",
    createdAt: "abcasdfwwsdgawdga",
    slug: "1234567890",
    id: 11,
    user: {
      img: "/user.png",
      username: "Pavan",
      id: "123",
    },
  },
  {
    img: "/demo.jpg",
    title: "Blog post title",
    body: "dxfcgvhbjhgvfcdfxfghksdbwgfvsdgjhfjbfuirfgaeugfbaegrtcfvgbhjnhfddtfcgvhbjnewrxctfvghbjbvfsxdfcgh",
    createdAt: "abcasdfwwsdgawdga",
    slug: "1234567890",
    id: 12,
    user: {
      img: "/user.png",
      username: "Pavan",
      id: "123",
    },
  },
  {
    img: "/demo.jpg",
    title: "Blog post title",
    body: "dxfcgvhbjhgvfcdfxfghksdbwgfvsdgjhfjbfuirfgaeugfbaegrtcfvgbhjnhfddtfcgvhbjnewrxctfvghbjbvfsxdfcgh",
    createdAt: "abcasdfwwsdgawdga",
    slug: "1234567890",
    id: 13,
    user: {
      img: "/user.png",
      username: "Pavan",
      id: "123",
    },
  },
  {
    img: "/demo.jpg",
    title: "Blog post title",
    body: "dxfcgvhbjhgvfcdfxfghksdbwgfvsdgjhfjbfuirfgaeugfbaegrtcfvgbhjnhfddtfcgvhbjnewrxctfvghbjbvfsxdfcgh",
    createdAt: "abcasdfwwsdgawdga",
    slug: "1234567890",
    id: 14,
    user: {
      img: "/user.png",
      username: "Pavan",
      id: "123",
    },
  },
  {
    img: "/demo.jpg",
    title: "Blog post title",
    body: "dxfcgvhbjhgvfcdfxfghksdbwgfvsdgjhfjbfuirfgaeugfbaegrtcfvgbhjnhfddtfcgvhbjnewrxctfvghbjbvfsxdfcgh",
    createdAt: "abcasdfwwsdgawdga",
    slug: "1234567890",
    id: 15,
    user: {
      img: "/user.png",
      username: "Pavan",
      id: "123",
    },
  },
  {
    img: "/demo.jpg",
    title: "Blog post title",
    body: "dxfcgvhbjhgvfcdfxfghksdbwgfvsdgjhfjbfuirfgaeugfbaegrtcfvgbhjnhfddtfcgvhbjnewrxctfvghbjbvfsxdfcgh",
    createdAt: "abcasdfwwsdgawdga",
    slug: "1234567890",
    id: 16,
    user: {
      img: "/user.png",
      username: "Pavan",
      id: "123",
    },
  },
];
