import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar/NavBar";
import Footer from "@/components/footer/Footer";
// import ClientProviderTest from "@/components/ClientProviderTest";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blogger Logger",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <ClientProviderTest> */}
      <body className={inter.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
      {/* </ClientProviderTest> */}
    </html>
  );
}
